# Scores to updatd when a player changes their name
uuid-based-scores:
  - deaths
  - 'num-advancements'
  - buildscore
  - votes

#whether to delete old scoreboard entries when a player changes their name.
reset-old-scores: true

#set the scoreboard behavior for transferring scores to new username - can be OVERWRITE or ADD
scoreboard-update-behavior: OVERWRITE
