name: ScoreboardUUID
main: net.evmodder.scoreboarduuid.ScoreboardUUID
authors: [EvModder/EvDoc,crashdemons]
version: 2.0
api-version: 1.13

#commands:
#   about:
#      description: View information about a player
#      usage: /about <name>
#      aliases: [seen,info]
#      permission: hardcore.about
#      permission-message: You do not have permission to do this.
#
#permissions:
#   hardcore.about:
#      description: Permission to use /about
#      default: true